config/routes.rb
Rails.application.routes.draw do
  # mount actioncable
  mount ActionCable.server => '/cable'
  
  root "spaces#index"
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  resources :spaces do
    resources :leases, only: [:new, :create, :show, :update]
  end
  resources :users, only: [:show]
  resources :images, only: [:index]
  resources :rooms, except: [:update, :edit, :destory]
  resources :messages, only: [:create]




    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :leases
  has_many :users, through: :leases
  has_many :images, inverse_of: :space, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
  geocoded_by :postal_code
  after_validation :geocode

  validates :name, presence: true
  validates :available_desks, presence: true, numericality: {only_integer: true}
  validates :description, presence: true
  validates :number, presence: true, numericality: true
  validates :street_name, presence: true
  validates :city, presence: true
  validates :province, presence: true
  #validates canadian postal code
  # canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
  # validates :postal_code, presence: true, format: { with: canadian_postal_code }
  validates :postal_code, presence: true





#finds all leases where lease status is 2(confirmed)
  def self.available_leases(space)
    leases = Lease.where(space_id: space.id)
    array = []
    leases.each do |lease|
      if lease.status_id == 2
        array << lease
      end
    end
    return array
  end

#takes collection of confirm leases and returns count of desks
  def self.taken_desks(array)
    count = 0
    array.each do |lease|
      count += lease.desks
    end
    return count
  end


  def self.user_has_lease?(user,space)
    office_id = Space.find(space.id).id
    leases = Lease.where(status_id: 1)
    if user
      leases.each do |lease|
        if lease.space_id == office_id && user.id == lease.user_id
          return true
        end
      end
    end
  return false
  end

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_logged_in, only: [:destroy, :edit, :update]

  def index
    @spaces = Space.all

    respond_to do |format|
      format.html
      format.json { render json: @spaces}
    end
  end

  def new
    @space = Space.new
    @space.images.build
  end

  def create
    @user = current_user
    @space = @user.owned_spaces.new(space_params)

    if @space.save
      flash[:sucess] = 'New Space succesfully added'
      redirect_to spaces_path
    else
      flash[:notice] = "this didnt save "
      render :new
    end
  end

  def show
    @space = Space.find(params[:id])
    @leases = @space.leases
    available_spaces = @space.available_desks
    available_leases = Space.available_leases(@space)
    taken_desks = Space.taken_desks(available_leases)
    @remaining_desks = available_spaces - taken_desks
    @price_per_desk = '%.2f' % @space.price
    @hash = Gmaps4rails.build_markers(@space) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
    if user_signed_in?
      @user_has_lease = Space.user_has_lease?(current_user, @space)
    else
      @user_has_lease = false
    end
  end

  def edit
    @space = Space.find(params[:id])
  end

  def update
    @user = current_user
    @space = Space.find(params[:id])
    if @space.update_attributes!(space_params)
      flash[:sucess] = 'project succesfully updated'
      redirect_to space_path(@space)
    else
      flash[:notice] = 'this didnt update'
      redirect_to root_path
    end
  end

  def destroy
    #important, if you destroy the space, you have to destroy the associated leases
    @space = Space.find(params[:id])
    Lease.where(space_id: @space.id).destroy_all
    @space.destroy
  end


  private

  def space_params
    params.require(:space).permit(:name,
                                  :description,
                                  :available_desks,
                                  :price,
                                  :user_id,
                                  :number,
                                  :street_name,
                                  :city,
                                  :province,
                                  :postal_code,
                                  images_attributes: [:id, :location_picture, :_destroy])
  end


  def ensure_logged_in
    @space = Space.find(params[:id])
    if current_user != User.find(@space.user_id)
      redirect_to spaces_path, notice: "you do not have access"
    end
  end


end


# to_query

# url    = 'http://www.foo.com?id=4&empid=6'
# uri    = URI.parse(url)
# params = CGI.parse(uri.query)
# # params is now {"id"=>["4"], "empid"=>["6"]}
#
# id     = params['id'].first
# # id is now "4"

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for @space, html: { multipart: true } do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="modal-bodies">


    <div class="modal-body modal-body-step-1 is-showing">
      <%= f.label 'Venue name' %>
      <%= f.text_field :name, placeholder: "Enter your venue's name" %><br/>
      <%= f.text_area :description, placeholder: "Describe your venue" %><br/>
      <button type="button">Start</button>
    </div>



   <div class="modal-body modal-body-step-2">
      <%= f.label 'Address'%><br/>
      <%= f.number_field :number, placeholder: "Number" %>
      <%= f.text_field :street_name, placeholder: "Enter Street Name" %><br/>
      <%= f.label :city %>
      <%= f.select :city, ['Toronto', 'Montreal', 'Vancouver'], { :prompt => "Select" }%>
      <%= f.label :province %>
      <%= f.select :province, ['BC','ON','QC'], { :prompt => "Select" }, placeholder: "Please select your province" %><br/>
      <%= f.label "postal code" %>
      <%= f.text_field :postal_code, placeholder: "Enter Postal Code" %><br/>
      <button type="button">Next</button>
   </div>



    <div class="modal-body modal-body-step-3">
      <%= f.label :available_desks %>
      <%= f.number_field :available_desks, placeholder: "Enter desks available" %>
      <%= f.label 'Price per desk' %>
      <%= f.number_field :price, placeholder: "Enter price per desk CDN$" %>
      <button type="button">Next</button>
    </div>




    <div class="modal-body modal-body-step-4">
      <div id = "upload_pictures">
        <p>Upload Images</p></br>
        <%= f.fields_for :images do |image| %>
          <%= render 'image_fields', :f => image %>
        <% end %>
        <div class="links">
          <%=link_to_add_association 'Add extra Image', f, :images %>
        </div>
        </br></br>
        <% unless @space.images.blank? %>
          <% @space.images.each do |image| %>
            <div class='imagetags'>
              <%= image_tag image.location_picture.url(:thumb) %>
            </div>
          <% end %>
        <% end %>

    </div>
      <%= f.submit 'Save Venue' %>
    <% end %>
   </div>

</div>

app/views/spaces/_image_fields.html.erb
<div class="nested-fields">
  <a class="field">
    <%= f.file_field :location_picture, :title => "Add Image" %>
  </a>
  <%= link_to_remove_association "Remove", f %>
  </br></br>
</div>

app/views/spaces/_interstitial.html.erb
<div class="int-body">
  <img class="int-logo" src= <%= asset_path('footer-logo.svg') %> alt="">
   <% if user_signed_in? %>
   <% else %>
  <li class="nav-item int-login"><span id = "log-in-button"><%= link_to "Log In", new_user_session_path %></span></li>
  <% end %>
  <div class="int-main-container">
    <h1 class="int-cta">Find your space. Launch your idea.</h1>
    <div class="int-btns">
      <div class="int-btn-1">Explore</div>
      <div class="int-btn-2">
      <%= link_to "List a space", new_space_path %>
    </div>
    </div>
    <div class="mouse">
    <div class="scroll"></div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(".mouse").click(function() {
    $('html,body').animate({
        scrollTop: $(".main-container").offset().top},
        'slow');
  });

  $(".int-btn-1").click(function() {
    $('html,body').animate({
        scrollTop: $(".main-container").offset().top},
        'slow');
  });
</script>

app/views/spaces/edit.html.erb
<%= render 'form', space: @space %>

app/views/spaces/index.html.erb
<div class = "index-page">

<div class="sort-tools">
  <h2>I'm looking for:</h2>
  <div class="dropdown">
  <select id="number-of-desks">
  <% for i in (1..30) %>
  <% if i == 1  %>
  <option value="<%= i %>"><%= "#{i} Desk "%></option>
  <% else %>
  <option value="<%= i %>"><%= "#{i} Desks "%></option>
  <% end %>
  <% end %>
  </select>
  </div>
  <div id="in" class="dropdown">
    <h2>in</h2>
  </div>
  <div class="dropdown">
    <select id="city">
      <option value="all">All Cities</option>
      <option value="toronto">Toronto</option>
      <option value="montreal">Montreal</option>
      <option value="vancouver">Vancouver</option>
    </select>
  </div>
</div>

<div class="results-container">
  <div id="search-results">
    <div class="space-info">
      <% @spaces.each_with_index do |space,val| %>
        <div class="space-box" id = "<%= val %>" >
          <p class="space-price">$<%= '%.2f' % space.price %></p>
          <%= link_to space_path(space), class: 'show-btn', id: "link#{val}" do %>
            <div class="space-hover">
              <p class="space-name"><strong><%= space.name %></strong></p>
              <p class="space-desks">Desks Available: <%= space.available_desks %></p>
            </div>

          <div class="front-page-img-container" id = "<%= val %>" >
              <%= image_tag space.images.first.location_picture.url(:original), class: 'front-page-img' if space.images.first  %>
              <% end %>
          </div>
          <br>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/spaces/new.html.erb
<%= render 'form' %>

app/views/spaces/show.html.erb
<div class="show-page-image-container">
<div class="my-slider">
  <ul>
    <% @space.images.each do |image| %>
    <li><%= image_tag image.location_picture.url(:original), class: "show-page-image" %></li>
    <% end %>
  </ul>
</div>
</div>


<div class="space-details-container">
  <% if current_user && current_user.id != @space.user_id %>
  <div class="message-user-icon" ><%= link_to image_tag("/images/ic_textsms_24px.svg"),
                                      rooms_path(user1_id:current_user.id,
                                                 user2_id:@space.user_id), method: :post %>
  </div>
    <div class="message-user-text">Chat with Owner</div>
  <% end %>
  <br><h3><%= "#{@space.name}" %></h3>
  <div class = 'toggle-info'>
    <div class="status">
      <% if current_user %>
        <% if @space.user.online %>
          <span>Owner Status: <%= image_tag "green_dot.png", id: "#{@space.user_id}-status", class: "active" %></span>
        <% else %>
          <span>Owner Status: <%= image_tag "green_dot.png", id: "#{@space.user_id}-status", class: "inactive"%></span>
        <% end %>
      <% end %>
      <% unless current_user %>
          <span>Please Login to communicated with owner</span>
      <% end %>
    </div>
    <p class = 'description' ><%= "#{@space.description}" %></p>

    <div class = "desks-requested"></div>
</div>
  <h4><%= "Desks Available: #{@remaining_desks}" %></h4>
  <div class="price_each_desk" value="<%= @price_per_desk %>">
  <span id='price'>Price per desk: $<span id='pricenumber'><%= @price_per_desk %></span> / month</span>
  </div>

  <% unless !current_user || @space.user.id == current_user.id %>
      <div class="total-price">Your total: $<span id='total-price-value'></span>/ month</div>
      <% unless @user_has_lease %>
    <%= link_to 'Request Reserved Space', new_space_lease_path(@space), {class: 'new-lease', remote: true} %>

    <br>
    <% end %>
  <% end %>
  <% if current_user && @space.user.id == current_user.id %>
    <%= link_to 'Edit Your Place', edit_space_path(@space)%>
  <% end %>

  <div id="new-lease-form"></div>
  <p class="notice"><%= notice %></p>
</div>


<div class="map-container">
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {scrollwheel: false}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
handler.getMap().setZoom(16);

});
</script>