config/routes.rb
Rails.application.routes.draw do
  # mount actioncable
  mount ActionCable.server => '/cable'
  
  root "spaces#index"
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  resources :spaces do
    resources :leases, only: [:new, :create, :show, :update]
  end
  resources :users, only: [:show]
  resources :images, only: [:index]
  resources :rooms, except: [:update, :edit, :destory]
  resources :messages, only: [:create]




    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cubicle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyAM8OlzB6fHkGMazggxdrzT9mHeg-PTmWA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <% if current_page?(root_path) %>
      <%= render "interstitial" %>
    <% end %>
    <div class="main-container">
      <nav>
        <div class="nav-content">
          <span class = "navbar-text">
         <% if user_signed_in? %>
           <li class="nav-item"><span id = "welcome-message" class = "<%= current_user.id  %>"> Hello, <%= link_to "#{current_user.first_name}", user_path(current_user) %></span></li>
           <li class="nav-item"><span id = "current_chats" class = "<%= current_user.id %>"><%= link_to image_tag("/images/ic_mail_outline_24px.svg"), rooms_path %><span id = "newmessage", class = "<%= active_or_inactive %>">!</span></span></li>
           <li class="nav-item"><span id = "user-icon" class = "<%= current_user.id  %>"> <%= link_to image_tag("/images/ic_person_24px.svg"), user_path(current_user) %></span></li>
           <li class="nav-item"><span id = "log-out-button"><%= link_to "Log out", destroy_user_session_path, :method => :delete %></span></li>
         <% else %>
           <li class="nav-item"><span id = "log-in-button"><%= link_to "Log In", new_user_session_path %></span></li>
           <li class="nav-item"><span id = "sign-up-button"><%= link_to "Sign Up", new_user_registration_path %></span></li>
         <% end %>
        </span>
        </div>
      </nav>
      <!-- <p class="notice"><%= notice %></p> -->
      <p class="alert"><%= alert %></p>
    <div class="width-control">
      <div class="header-container">
      <a href="/spaces">
    <img id="logo" src= <%= asset_path('logo.svg') %> alt="">
    </a>
    </div>
    <div class="add-space">
      <%= link_to "List a space", new_space_path %>
    </div>
    <%= yield %>
    </div>
  </div>
  <footer>
    <div class="width-control">
      <div class="row">
        <div class="col">
          <img id="footer-logo" src=<%= asset_path('footer-logo.svg') %> alt="">
          <p class="footer-link">Cubicl LTD.  ®  2016</p>
        </div>
        <div class="col">
          <h4 class="footer-heading">About Us</h4>
          <p class="footer-link">Our Policy</p>
          <p class="footer-link">Frequently Asked Questions</p>
          <p class="footer-link">Support</p>
        </div>
        <div class="col">
          <h4 class="footer-heading">Follow Us</h4>
          <p class="footer-link">Facebook</p>
          <p class="footer-link">Instagram</p>
          <p class="footer-link">LinkedIn</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>